# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0013_auto_20170310_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.PositiveIntegerField()),
                ('max_price', models.PositiveIntegerField()),
                ('min_area', models.PositiveIntegerField()),
                ('max_area', models.PositiveIntegerField()),
                ('min_room', models.PositiveIntegerField()),
                ('max_room', models.PositiveIntegerField()),
                ('house', models.BooleanField(default=True)),
                ('appartment', models.BooleanField(default=True)),
                ('furnished', models.PositiveIntegerField(choices=[(1, 'Meublé'), (2, 'Non Meublé')])),
                ('locations', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('l', 'locations'), ('v', 'ventes_immobilieres')], default='l', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
