# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0014_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='max_area',
            field=models.PositiveIntegerField(choices=[(0, '0 m²'), (1, '20 m²'), (2, '25 m²'), (3, '30 m²'), (4, '35 m²'), (5, '40 m²'), (6, '50 m²'), (7, '60 m²'), (8, '70 m²'), (9, '80 m²'), (10, '90 m²'), (11, '100 m²')]),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='min_area',
            field=models.PositiveIntegerField(choices=[(0, '0 m²'), (1, '20 m²'), (2, '25 m²'), (3, '30 m²'), (4, '35 m²'), (5, '40 m²'), (6, '50 m²'), (7, '60 m²'), (8, '70 m²'), (9, '80 m²'), (10, '90 m²'), (11, '100 m²')]),
        ),
    ]
