# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0015_auto_20170312_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='category',
            field=models.CharField(choices=[('locations', 'Locations'), ('ventes_immobilieres', 'Ventes')], max_length=255),
        ),
    ]
