# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0016_auto_20170312_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='search_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
